import {Inter } from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/ui/header";
import { ClerkProvider } from "@clerk/nextjs";
  
const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning >
      <body className={`${inter.className}`}
       >
       <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/*  header */}
            <Header />
             <footer className="bg-muted/50 py-12 ">
            <div className=" container mx-auto px-4 text-center text-gray-200  ">
              <p>
                Made with 💗 by Ankit Kumar
              </p>

            </div>



            </footer>

            {children}
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
